### PR TITLE
Custom content references

### PR DESCRIPTION
**Pull request by jdrummey**
New features for VIZ_IMAGE() plus new content references VIZ_CSV(), VIZ_PDF(), and VIZ_LINK()

### CODE REVIEW

**Comment by mcoles** [comment]
When publishing VizAlertsDemo.twb, Tableau looks for file references that live on your personal DropBox account. You can get around that by telling it _not_ to embed credentials, but that's a bit confusing because one of the requirements to subscribe to a View is that the connection use embedded credentials. Any way to make the publishing process easier? Maybe keep all the files local in the Demo folder?

**Comment by mcoles** [comment]
I ran the Advanced Alerts Stress Test on VizAlertsDemo after changing the To / From parameters, and found that it sent me three error emails, with the following content in the body:

Alert was triggered, but unable to process arguments to a content reference with error Found an invalid or non-allowed separator in filename: bar\foo for content reference VIZ_CSV(VizAlertsDemo/Overview|filename=bar\foo)

Alert was triggered, but encountered a failure getting data/image references: Found an invalid or non-allowed separator in filename: bar\foo for content reference VIZ_CSV(VizAlertsDemo/Overview|filename=bar\foo)

VizAlerts was unable to process this view due to the following error: Found an invalid or non-allowed separator in filename: bar\foo for content reference VIZ_CSV(VizAlertsDemo/Overview|filename=bar\foo)

Is this expected? Getting three error emails from a single Advanced Alert test is a bit confusing. It would be my preference that for all errors we can detect _up front_, we consolidate all of them in a single email and let the owner know about all of them at once. This is done for any issues found with invalid Recipients in the current VizAlerts implementation. That one will use an HTML table to describe each issue and the line in the CSV where it was found, and it'll also attach the CSV in question. This could do the same thing for invalid characters found (though I don't think it should have to do the same for a bad content reference that required exporting Tableau Server content--I say we bail on the first failed attempt for that category of error).

**Comment by mcoles** [comment]
When I run the Advanced Alerts Stress Test on VizAlertsDemo.twb with the To / From parameters reflecting domains that are _not_ allowed by the config file whitelist, VizAlerts logs that it is trying to send the Admin and view Owner a failure email, but it never actually does so. Instead, it logs this error when it tries to send the email:

2016-03-29 08:16:18 - [ERROR] - send_email - Email failed to send: string indices must be integers
2016-03-29 08:16:18 - [ERROR] - view_failure - Unknown error sending exception alert email: string indices must be integers

**Comment by jdrummey** [comment]
re: the Dropbox reference. I'd tried to have everything in the same folder but failed, obviously. I can fix that.

re: three emails on failure. I'd seen it and forgotten about it, and then just noticed that the other day, it has something to do with how exceptions are raised vis-a-vis the "email the admin on failure" code that I don't understand. I'll have to spend some quality time with the code (and maybe learn more about exception handling in Python).

re: stress test emails. Which one was being sent? The way I tested that was to filter the view for one at a time because a) they are designed to fail and b) when Tableau generates the trigger view CSV it does its own sort.

Jonathan

**Comment by mcoles** [comment]
Ah, I see--I had been running the entire block of stress tests as a single alert. Sounds like that's not the way to run it properly. In that particular case, I had used Email Sort Order to sort by Test #, so you can repro by doing the same and test_alert-ing the entire view.

One other thing I noticed about the failure emails in another test I did is that the footer, which lists the View URL, is actually listing the URL of the view to be embedded by the VIZ_IMAGE() content reference, rather than the trigger view itself. The two symptoms may be related, I'm not sure, but both should be fixed.

**Comment by mcoles** [comment]
I notice that I can pass characters into the |filename parameter that are not normally valid in a file, such as ":". The character gets preserved in the email format itself, but I notice that Outlook normalizes the name to an OS-friendly filename. As an example, if I attach two of the same files like so:

VIZ_IMAGE(Book4/AccountTotalSpend|filename=testfile:name)
VIZ_IMAGE(Book4/AccountTotalSpend|filename=testfilename)

These don't cause VizAlerts to complain, nor my test mail client PaperCut. If I open the same email in Outlook, I noticed that now both attachments have duplicate filenames. When you then try to "download all attachments", it complains about the file already existing.

Thinking about it, I'm not totally sure we should incorporate logic that tests for invalid filename characters and fail if any are included...since that would probably be a worse outcome than simply having to save each attachment individually. Just wanted to note this behavior because I find that it's interesting. In your testing with other email clients, do you know if they can handle attachments with duplicate filenames?

**Comment by mcoles** [comment]
This isn't a complaint or question, I just wanted to note another use case that is solved by your new code, Jonathan--embedding arbitrary hosted images. I have an alert that uses an HTML  tag and references an image that I host publicly on my Dropbox account. But it's a pain because many folks don't load externally hosted images by default. But if I _do_ host them internally, then users connecting to email without being on the VPN can't access them!

The way this code solves my problem is this: I can now author a Tableau Server view that contains the image I need to "host", then simply reference _that_ in my Advanced Alert! Now the actual image is no longer a simple reference to an image somewhere on the Internet--it's embedded as a PNG, so everyone can see it in all situations. Booyah! :)

**Comment by jdrummey** [comment]
re: allowed characters in filenames/dup filenames - There's actually code to prevent duplicate filenames and I'd missed that test case, I hadn't realized the mail program or OS would try to be that smart. I think I want to add a check for allowed characters, I don't think there's much sense in users being able to create something that isn't accurate, and even more so I think it helps avoid potential problems with users trying to do something sneaky with a filesystem. One of the reasons why I like using | as a delimiter is that it prevents pipe problems. I'm thinking of disallowing `~!@#$%^&*()=[]{}\;:'",<>?/., so the allowed characters for filenames would be any alpha or numeric, -_+, space, and period.

re: the stress tests. a) I'll have to document how to use the Other Tests/stress tests. b) The Email Sort order field doesn't do anything unless Email Consolidate is also used, so either you'll need to hunt through logs or duplicate the error for me to be able to better figure out the problem. (I'll also test on my end when I can). The reason why the Sort Order doesn't do anything w/out consolidation is because there's no way we can control the order of delivery due to caching by email servers, so the only applicable use of sorting is to make sure consolidation happens in the order that we want.

re: failure emails. I'll have to look at that, I agree that the default footer should only be rendering a link to the trigger view.

re: embedding arbitrary hosted images. Have you tried that out yet? I seem to remember something about URL objects not being included in downloaded PNG or PDFs, while image objects _are_ included. I just did a quick test and verified that is the behavior.

**Comment by mcoles** [comment]
re: embedding arbitrary hosted images, I wasn't meaning that Tableau Server would act as a sort of proxy for images hosted on the Internet, but rather that by publishing a view referencing an image _included_ with the workbook, you had a way you could (manually) host images on Tableau Server and therefore physically embed them in your alert. MyImagesWorkbook\cat, MyImagesWorkbook\dog, MyImagesWorkbook\confetti can now be embedded in any alert you like, and the images will always show up for people in their mail client.

**Comment by jdrummey** [comment]
Ok, that makes sense.

**Comment by mcoles** [comment]
re: failure emails: So, I believe this is occurring because view_failure is called each time we're raising an exception in find_viz_refs. That function sends an email each time it's called, so we're sending basically the same email multiple times as the error is being passed back up the stack. I'm testing a change on my local version of your branch that might fix this.

re: string indices must be integers error in send_email: This is when a recipient is invalid (doesn't match domain whitelist, doesn't look like a proper email address, etc). We're trying to attach the CSV of the trigger view so that users can figure out what line(s) caused the issue and caused the alert to fail. Line 643 is passing the csvpath as the Inline attachments, not the appended attachments.

_edit_: It's also that we're just passing in a string pointing to the path of the attachment...the new version of send_email expects the object to be...a list of dicts with the parameters and such? (still trying to wrap my head around that...might be helpful to have an Attachment class or somesuch to encapsulate the new concept of an attachment)

**Comment by mcoles** [comment]
re: failure emails: I made some changes to the error handling that fixed the multiple-emails problem. If you want, I can send them to you, or else I'll just accept the pull request then submit my own changes on that branch of the main repo.

re: string indices must be integers error in send_email: If you don't pass in the attachment on line 643, it works fine. So we just need to find the right way to pass a generic CSV attachment to send_email when it's not really a vizref. I'm going to let you figure that one out.

I'm thinking about building some Python classes for the next release to help improve the readability and coherency of the code. Just thoughts right now, but I'll send you what I have after I think I have something workable.

**Comment by jdrummey** [comment]
re: failure emails: Thanks for figuring it out! If you want to accept the
pull request that's probably fastest right now, then the corrections I make
(likely this weekend) can be new requests on the main branch.

re: string indices: I'll figure that one out, I'm betting it's a change in
one line: Based on past experience with this error I'm either passing a
dict that needs to be a list or send_email is expecting a list when it
should be expecting a list.

re: Python classes. I'm not quite seeing how that would work, I don't know
enough about OO. If you think it would make the code more readable I'm all
for it, tho!

**Comment by jdrummey** [comment]
re: stress tests email failure: I have a fix for that...to get the attachments to work the attachment code in send_email() requires that each attachment be represented by a dictionary where the minimal dict is {'imagepath': [path to downloaded file to attach']}.

The error was being caused by the send_email() code looking for a dictionary and getting a string because I hadn't updated the view_failure() for the change. I've updated the view_failure() code and added more details to the send_email code.

**Comment by jdrummey** [comment]
re: Dropbox references. I deleted the references from the VizAlertsDemo.twb file. However as far as i can tell anytime the twb changes Tableau automatically inserts the exact references so we'll need to keep track of that.

re: filenames. I added the code to only allow alphanumeric, underscore, hyphen, space, period, and plus sign. The regex uses the the $L locale argument to support accented characters in other locales.

I'll be deleting this pull request and creating a new one in a minute.

**Pull request closed without merging**
